name: Release Drafter
description: Create release draft based on pull requests merged since last release.

inputs:
  github-token:
    description: GITHUB_TOKEN secret
    required: true

runs:
  using: composite

  steps:
    - if: ${{ github.repository_owner == 'brdgm' }}
      uses: release-drafter/release-drafter@v6
      with:
        disable-autolabeler: true
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
